const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const rootDir = path.join(__dirname, '..');

function readPublicAiMusicFile(filePath) {
  return fs.readFileSync(path.join(rootDir, 'public', 'ai-music', filePath), 'utf8');
}

test('ai music page shell is installed under public route', () => {
  const html = readPublicAiMusicFile('index.html');

  assert.match(html, /<title>AI 音乐<\/title>/);
  assert.match(html, /<meta property="og:title" content="AI 音乐">/);
  assert.match(html, /<meta name="twitter:title" content="AI 音乐">/);
  assert.match(html, /<div id="app"><\/div>/);
  assert.match(html, /href="\/ai-music\/assets\/styles\.css\?v=/);
  assert.match(html, /href="\/ai-music\/assets\/my-music\.css\?v=/);
  assert.match(html, /src="\/ai-music\/assets\/app\.js\?v=/);
  assert.doesNotMatch(html, /(?:href|src)="\.\/assets\//);
  assert.doesNotMatch(html, /教父音乐|教父/);
});

test('ai music frontend uses Claw800 API routes instead of user API keys', () => {
  const apiJs = readPublicAiMusicFile('assets/api.js');
  const authJs = readPublicAiMusicFile('assets/auth.js');
  const appJs = readPublicAiMusicFile('assets/app.js');
  const combined = `${apiJs}\n${authJs}\n${appJs}`;

  assert.doesNotMatch(combined, /hh_x|gm_api_key|API Key|accounts\/api/);
  assert.match(apiJs, /\/api\/ai-music\/music/);
  assert.match(apiJs, /\/api\/ai-music\/media/);
  assert.match(authJs, /nexaauth:\/\/oauth\/authorize/);
  assert.match(authJs, /nexaauth:\/\/order/);
  assert.match(authJs, /function isNexaAppEnvironment\(\)/);
  assert.match(authJs, /openNexaDownloadModal/);
  assert.match(authJs, /https:\/\/nexa\.ceo/);
  assert.match(authJs, /if \(!isNexaAppEnvironment\(\)\) \{[\s\S]*openNexaDownloadModal\(\);[\s\S]*return false;/);
  assert.match(authJs, /const started = await startNexaLogin\(\);[\s\S]*if \(started\) onSuccess/);
  assert.match(authJs, /paySign/);
  assert.match(combined, /\/api\/ai-music\/credits\/order/);
});

test('ai music purchase flow shows three Nexa package choices', () => {
  const apiJs = readPublicAiMusicFile('assets/api.js');
  const authJs = readPublicAiMusicFile('assets/auth.js');
  const appJs = readPublicAiMusicFile('assets/app.js');
  const generateJs = readPublicAiMusicFile('assets/generate.js');
  const libraryJs = readPublicAiMusicFile('assets/library.js');
  const myJs = readPublicAiMusicFile('assets/my.js');
  const stylesCss = readPublicAiMusicFile('assets/styles.css');
  const combined = `${apiJs}\n${authJs}\n${appJs}`;

  assert.match(apiJs, /createCreditOrder\(tier/);
  assert.match(apiJs, /refreshCreditOrder\(orderNo\)/);
  assert.match(authJs, /AI_MUSIC_PACKAGES/);
  assert.match(authJs, /AI_MUSIC_PENDING_PAYMENT_STORAGE_KEY/);
  assert.match(authJs, /savePendingCreditOrder/);
  assert.match(authJs, /refreshPendingCreditOrder/);
  assert.match(authJs, /tier:\s*'1u'[\s\S]*amount:\s*'1\.00'[\s\S]*credits:\s*2/);
  assert.match(authJs, /tier:\s*'10u'[\s\S]*amount:\s*'10\.00'[\s\S]*credits:\s*25/);
  assert.match(authJs, /tier:\s*'100u'[\s\S]*amount:\s*'100\.00'[\s\S]*credits:\s*300/);
  assert.match(authJs, /openBuyCreditsModal/);
  assert.match(authJs, /window\.dispatchEvent\(new CustomEvent\('gm-credits-changed'/);
  assert.match(combined, /openBuyCreditsModal/);
  assert.match(appJs, /let active = 'square'/);
  assert.match(appJs, /location\.hash\.replace\('#', ''\) \|\| 'square'/);
  assert.match(appJs, /class:\s*'gm-brand'[\s\S]*href:\s*'\/ai-music\/#square'/);
  assert.match(appJs, /text:\s*'AI 音乐'/);
  assert.doesNotMatch(appJs, /text:\s*'🎵 AI 音乐'/);
  assert.match(appJs, /refreshPendingCreditOrder/);
  assert.match(appJs, /window\.addEventListener\('pageshow'/);
  assert.match(appJs, /window\.addEventListener\('focus'/);
  assert.match(appJs, /document\.addEventListener\('visibilitychange'/);
  assert.match(appJs, /let shellReady = false/);
  assert.match(appJs, /function renderBootLoading\(\)/);
  assert.match(appJs, /async function init\(\) \{[\s\S]*renderBootLoading\(\);[\s\S]*await bootstrapSession\(\);[\s\S]*boot\(\);/);
  assert.match(appJs, /window\.addEventListener\('gm-auth-changed'[\s\S]*if \(!shellReady\) return;/);
  assert.match(appJs, /gm-credits-changed/);
  assert.match(appJs, /key:\s*'my'[\s\S]*label:\s*'我的'/);
  assert.match(appJs, /href:\s*'\/ai-music\/#my'[\s\S]*text:\s*'我的'/);
  assert.match(appJs, /navKeyFor/);
  assert.match(appJs, /loadScreenModule/);
  assert.match(appJs, /ALWAYS_RERENDER = new Set\(\['my'/);
  assert.match(appJs, /key:\s*'library'[\s\S]*label:\s*'我的音乐'[\s\S]*hidden:\s*true/);
  assert.match(appJs, /key:\s*'assets'[\s\S]*label:\s*'资产'[\s\S]*hidden:\s*true/);
  assert.match(myJs, /renderMy/);
  assert.match(myJs, /import \{ renderLibrary \}/);
  assert.match(myJs, /import \{ renderAssets \}/);
  assert.match(myJs, /key:\s*'library'[\s\S]*label:\s*'我的音乐'/);
  assert.match(myJs, /key:\s*'assets'[\s\S]*label:\s*'我的资产'/);
  assert.match(myJs, /key:\s*'nickname'[\s\S]*label:\s*'我的昵称'/);
  assert.match(myJs, /renderLibrary\(panel\)/);
  assert.match(myJs, /renderAssets\(panel,\s*\{\s*embedded:\s*true\s*\}\)/);
  assert.doesNotMatch(myJs, /href:\s*'\/ai-music\/#library'/);
  assert.match(myJs, /text:\s*'我的昵称'/);
  assert.match(myJs, /nicknameChangesRemaining/);
  assert.match(myJs, /每 30 天可修改一次/);
  assert.match(myJs, /api\.updateProfile/);
  assert.match(libraryJs, /let activeLibraryRoot = null/);
  assert.match(libraryJs, /function getLibRoot\(\) \{ return activeLibraryRoot \|\| document\.getElementById\('screen-library'\); \}/);
  assert.match(stylesCss, /\.gm-my-tabs/);
  assert.match(stylesCss, /\.gm-my-tab\.active/);
  assert.match(stylesCss, /\.gm-my-panel/);
  assert.match(appJs, /key:\s*'square'[\s\S]*label:\s*'广场'/);
  assert.match(appJs, /class:\s*'gm-btn-ghost sm gm-write-top'/);
  assert.match(appJs, /href:\s*'\/ai-music\/#generate'[\s\S]*text:\s*'写歌'[\s\S]*marketLink/);
  assert.match(appJs, /class:\s*'gm-btn-ghost sm gm-square-top'/);
  assert.match(appJs, /href:\s*'\/ai-music\/#square'[\s\S]*text:\s*'广场'/);
  assert.match(stylesCss, /\.gm-btn-ghost\.gm-write-top\{[^}]*background:var\(--grad\)[^}]*color:#fff/);
  assert.doesNotMatch(appJs, /gm-credits-chip/);
  assert.doesNotMatch(appJs, /text:\s*'充值'/);
  assert.match(generateJs, /openBuyCreditsModal/);
  assert.match(generateJs, /id="cf-recharge"[\s\S]*充值/);
  assert.match(generateJs, /id="proDocsBtn"[\s\S]*📖 文档/);
  assert.match(generateJs, /id="proDocsModal"[\s\S]*AI音乐提示词文档/);
  assert.match(generateJs, /id="gm-doc-overview"[\s\S]*id="gm-doc-fields"[\s\S]*id="gm-doc-syntax"[\s\S]*id="gm-doc-tags"[\s\S]*id="gm-doc-faq"/);
  assert.match(generateJs, /标签速查[\s\S]*常用模板[\s\S]*提交前检查/);
  assert.match(generateJs, /发音不准怎么办/);
  assert.match(generateJs, /Mandarin pop ballad/);
  assert.match(generateJs, /Ancient Chinese/);
  assert.match(generateJs, /Future bass/);
  assert.match(generateJs, /Rain ambience/);
  assert.match(generateJs, /proDocsBtn'\)\.addEventListener\('click'[\s\S]*docsModal\.style\.display = 'flex'/);
  assert.doesNotMatch(generateJs, /ai6666\.com\/docs/);
  assert.doesNotMatch(generateJs, /音乐教父|Godfather Music/);
  assert.match(stylesCss, /\.gm-pro-docs-body/);
  assert.match(stylesCss, /\.gm-pro-docs-head\{[^}]*position:sticky[^}]*z-index:3/);
  assert.match(stylesCss, /\.gm-pro-docs-index/);
  assert.match(stylesCss, /\.gm-pro-docs-index\{[^}]*position:sticky[^}]*top:58px/);
  assert.match(stylesCss, /\.gm-pro-docs-grid/);
  assert.match(apiJs, /updateProfile:\s*\(\{\s*nickname/);
  assert.match(authJs, /openProfileModal/);
  assert.match(authJs, /ensureProfileComplete/);
  assert.match(authJs, /请填写昵称/);
  assert.match(appJs, /ensureProfileComplete/);
  assert.doesNotMatch(appJs, /text:\s*'购买'/);
  assert.doesNotMatch(appJs, /text:\s*'退出'/);
  assert.match(generateJs, /gm-credits-changed/);
  assert.match(generateJs, /每个用户免费赠送1次/);
  assert.match(generateJs, /gm-free-credit-note/);
  assert.match(generateJs, /pushPendingGen\(\{\s*id:\s*pendingId[\s\S]*local:\s*true[\s\S]*status:\s*'submitting'/);
  assert.match(generateJs, /jumpLibraryNow\(\);[\s\S]*const result = await api\.generate\(payload\)/);
  assert.match(generateJs, /function extractGenerationId\(result = \{\}\)/);
  assert.match(generateJs, /replacePendingGen\(pendingId/);
  assert.match(generateJs, /removePendingGen\(pendingId\)/);
  assert.match(libraryJs, /if \(g\.local\) \{[\s\S]*status:\s*'submitting'/);
  assert.match(libraryJs, /window\.addEventListener\('gm-pending-gens-changed'/);
  assert.match(generateJs, /api\.generate\(payload\)[\s\S]*window\.dispatchEvent\(new CustomEvent\('gm-credits-changed'/);
  assert.match(libraryJs, /\/ai-music\/song\/\$\{encodeURIComponent\(String\(s\.id/);
  assert.match(libraryJs, /我在 https:\/\/claw800\.com\/ai-music\/ 用 AI 1 分钟做了首歌/);
  assert.doesNotMatch(libraryJs, /我在 ai6666/);
});

test('ai music is listed in games hub and served by express route', () => {
  const gamesConfig = fs.readFileSync(path.join(rootDir, 'public', 'games-config.js'), 'utf8');
  const dbJs = fs.readFileSync(path.join(rootDir, 'src', 'db.js'), 'utf8');
  const serverJs = fs.readFileSync(path.join(rootDir, 'src', 'server.js'), 'utf8');

  assert.match(gamesConfig, /slug:\s*'ai-music'/);
  assert.match(gamesConfig, /route:\s*'\/ai-music\/'/);
  assert.match(gamesConfig, /actionText:\s*'生成音乐'/);
  assert.match(gamesConfig, /slug:\s*'ai-music'[\s\S]*?sort_order:\s*100/);
  assert.match(gamesConfig, /getVisibleGames\(items\)[\s\S]*?\.sort\(\(a, b\) => \(Number\(b\.sort_order\) \|\| 0\) - \(Number\(a\.sort_order\) \|\| 0\)\)/);
  assert.match(dbJs, /slug:\s*'ai-music'/);
  assert.match(dbJs, /slug:\s*'ai-music'[\s\S]*?sort_order:\s*100/);
  assert.match(dbJs, /UPDATE games_catalog[\s\S]*slug = 'ai-music'[\s\S]*sort_order < 100/);
  assert.match(serverJs, /app\.get\(\['\/ai-music',\s*'\/ai-music\/',\s*'\/ai-music\/song\/:songId'\]/);
  assert.match(serverJs, /'ai-music':\s*'\/ai-music\/'/);
});

test('admin exposes ai music key, orders, and callback log management', () => {
  const adminHtml = fs.readFileSync(path.join(rootDir, 'public', 'admin.html'), 'utf8');
  const adminJs = fs.readFileSync(path.join(rootDir, 'public', 'admin.js'), 'utf8');
  const serverJs = fs.readFileSync(path.join(rootDir, 'src', 'server.js'), 'utf8');

  assert.match(adminHtml, /name="aiMusicApiBaseUrl"/);
  assert.match(adminHtml, /name="aiMusicApiKey"/);
  assert.match(adminHtml, /id="ordersAiMusicBtn"/);
  assert.match(adminHtml, /id="ordersAiMusicRechargeOrdersBtn"/);
  assert.match(adminHtml, /id="ordersAiMusicMarketOrdersBtn"/);
  assert.match(adminHtml, /id="ordersAiMusicWithdrawalsBtn"/);
  assert.match(adminHtml, /id="adminAiMusicRechargeOrdersSection"/);
  assert.match(adminHtml, /id="adminAiMusicMarketOrdersSection"/);
  assert.match(adminHtml, /id="adminAiMusicWithdrawalsSection"/);
  assert.match(adminHtml, /id="ordersAiMusicCallbackLogsBtn"/);
  assert.match(adminJs, /SAVED_AI_MUSIC_API_KEY_MASK/);
  assert.match(adminJs, /\/api\/admin\/ai-music-orders/);
  assert.match(adminJs, /\/api\/admin\/ai-music-recharge-orders/);
  assert.match(adminJs, /\/api\/admin\/ai-music-market-orders/);
  assert.match(adminJs, /\/api\/admin\/ai-music-withdrawals/);
  assert.match(adminJs, /approveAiMusicWithdrawal/);
  assert.match(adminJs, /rejectAiMusicWithdrawal/);
  assert.match(adminJs, /\/api\/admin\/ai-music-callback-logs/);
  assert.match(serverJs, /\/api\/admin\/ai-music-orders/);
  assert.match(serverJs, /\/api\/admin\/ai-music-recharge-orders/);
  assert.match(serverJs, /\/api\/admin\/ai-music-market-orders/);
  assert.match(serverJs, /\/api\/admin\/ai-music-withdrawals/);
  assert.match(serverJs, /\/api\/admin\/ai-music-callback-logs/);
});

test('ai music mobile inputs keep 16px text to prevent iOS focus zoom', () => {
  const styles = readPublicAiMusicFile('assets/styles.css');

  assert.match(styles, /@media\s*\(max-width:\s*768px\)/);
  assert.match(styles, /\.gm-input[\s\S]*font-size:\s*16px\s*!important/);
  assert.match(styles, /@media\s*\(max-width:\s*680px\)[\s\S]*\.gm-auth[\s\S]*gap:\s*4px/);
  assert.match(styles, /\.gm-modal\{[^}]*overflow:auto/);
  assert.match(styles, /\.gm-modal-card\{[^}]*width:min\(380px,calc\(100vw - 32px\)\)[^}]*max-height:calc\(100svh - 32px\)/);
  assert.match(styles, /\.gm-nexa-download-card\{[^}]*display:flex[^}]*flex-direction:column/);
  assert.match(styles, /\.gm-nexa-download-card > \.gm-btn-primary,[\s\S]*\.gm-nexa-download-card > \.gm-btn-ghost\{[^}]*width:100%/);
  assert.match(styles, /@media\(max-width:420px\)[\s\S]*\.gm-modal-card\{width:calc\(100vw - 24px\)/);
  assert.match(styles, /\.cf-scope textarea[\s\S]*font-size:\s*16px\s*!important/);
  assert.match(styles, /\.cf-scope input[\s\S]*font-size:\s*16px\s*!important/);
  assert.match(styles, /\.gm-st-scope input[\s\S]*font-size:\s*16px\s*!important/);
  assert.match(styles, /\.gm-st-scope select[\s\S]*font-size:\s*16px\s*!important/);
});

test('ai music shell and assets avoid stale Nexa webview caches', () => {
  const html = readPublicAiMusicFile('index.html');
  const appJs = readPublicAiMusicFile('assets/app.js');
  const authJs = readPublicAiMusicFile('assets/auth.js');
  const generateJs = readPublicAiMusicFile('assets/generate.js');
  const libraryJs = readPublicAiMusicFile('assets/library.js');
  const stemlabJs = readPublicAiMusicFile('assets/stemlab.js');
  const studioJs = readPublicAiMusicFile('assets/studio.js');
  const serverJs = fs.readFileSync(path.join(rootDir, 'src', 'server.js'), 'utf8');
  const combinedModules = `${appJs}\n${authJs}\n${generateJs}\n${libraryJs}\n${stemlabJs}\n${studioJs}`;

  assert.match(html, /\/ai-music\/assets\/styles\.css\?v=/);
  assert.match(html, /\/ai-music\/assets\/my-music\.css\?v=/);
  assert.match(html, /\/ai-music\/assets\/app\.js\?v=/);
  assert.match(appJs, /from '\.\/api\.js\?v=/);
  assert.match(appJs, /from '\.\/auth\.js\?v=/);
  assert.doesNotMatch(appJs, /from '\.\/(?:generate|library|assets|market|square|public-song|stemlab|studio|player)\.js\?v=/);
  assert.match(appJs, /import\(`\.\/\$\{screen\.module\}\.js\?v=/);
  assert.match(appJs, /renderBootLoading\(\);[\s\S]*handleNexaAuthCallback\(\)[\s\S]*await bootstrapSession\(\);[\s\S]*boot\(\);/);
  assert.match(authJs, /from '\.\/api\.js\?v=/);
  assert.doesNotMatch(combinedModules, /from '\.\/(?:api|auth|ui)\.js'/);
  assert.match(serverJs, /app\.get\(\['\/ai-music', '\/ai-music\/', '\/ai-music\/song\/:songId'\][\s\S]*Cache-Control', 'no-store/);
  assert.match(serverJs, /filePath\.includes\(path\.join\('public', 'ai-music'\)\)[\s\S]*Cache-Control', 'no-store/);
});

test('ai music uses persistent bottom player with scrolling lyrics', () => {
  const appJs = readPublicAiMusicFile('assets/app.js');
  const assetsJs = readPublicAiMusicFile('assets/assets.js');
  const generateJs = readPublicAiMusicFile('assets/generate.js');
  const libraryJs = readPublicAiMusicFile('assets/library.js');
  const apiJs = readPublicAiMusicFile('assets/api.js');
  const playerJs = readPublicAiMusicFile('assets/player.js');
  const squareJs = readPublicAiMusicFile('assets/square.js');
  const publicSongJs = readPublicAiMusicFile('assets/public-song.js');
  const marketJs = readPublicAiMusicFile('assets/market.js');
  const styles = readPublicAiMusicFile('assets/styles.css');

  assert.match(appJs, /initGlobalPlayer/);
  assert.match(generateJs, /toggleGlobalSong/);
  assert.match(libraryJs, /toggleGlobalSong/);
  assert.match(libraryJs, /api\.remakePreset/);
  assert.match(libraryJs, /sessionStorage\.setItem\('gm_remake'/);
  assert.match(libraryJs, /new Event\('gm-remake-handoff'\)/);
  assert.match(generateJs, /bindRemakeHandoffListener/);
  assert.match(generateJs, /window\.addEventListener\('gm-remake-handoff'/);
  assert.match(generateJs, /switchMode\(root,\s*'lyrics'\)/);
  assert.match(generateJs, /已带入专业模式，可修改后重新生成/);
  assert.match(apiJs, /songLyrics:\s*\(id\)\s*=>\s*request\('GET',\s*`\/song\/\$\{id\}\/lyrics`/);
  assert.match(apiJs, /songLrc:\s*\(id\)\s*=>\s*request\('GET',\s*`\/song\/\$\{id\}\/download-lrc`/);
  assert.match(libraryJs, /data-act="lyrics"/);
  assert.match(libraryJs, /api\.songLyrics/);
  assert.match(playerJs, /import\s+\{\s*api\s*\}\s+from '\.\/api\.js\?v=/);
  assert.match(playerJs, /api\.songLyrics/);
  assert.match(playerJs, /api\.songLrc/);
  assert.match(playerJs, /api\.songDetail/);
  assert.match(playerJs, /lrc_lines/);
  assert.match(playerJs, /startS/);
  assert.match(playerJs, /parseLyricTimestamp/);
  assert.match(playerJs, /hasTimedLyrics/);
  assert.match(playerJs, /needsSyncedLyricsFetch/);
  assert.match(playerJs, /line\.time\s*<=\s*currentTime/);
  assert.match(apiJs, /publicSongs:\s*\(/);
  assert.match(apiJs, /publicSong:\s*\(id\)/);
  assert.match(apiJs, /publicSongLyrics:\s*\(id\)/);
  assert.match(apiJs, /recordPublicPlay:\s*\(id\)/);
  assert.match(apiJs, /marketListings:\s*\(/);
  assert.match(apiJs, /createMarketOrder:\s*\(listingId\)/);
  assert.match(apiJs, /listSong:\s*\(id,\s*price\)/);
  assert.match(apiJs, /assets:\s*\(\)\s*=>\s*appRequest\('GET',\s*ASSET_API_BASE\)/);
  assert.match(apiJs, /withdrawAssets:\s*\(amount\)/);
  assert.match(appJs, /renderMarket/);
  assert.match(appJs, /key:\s*'market'[\s\S]*label:\s*'市场'/);
  assert.match(marketJs, /text:\s*'音乐市场-版权自由交易'/);
  assert.match(assetsJs, /renderAssets/);
  assert.match(assetsJs, /api\.assets/);
  assert.match(assetsJs, /api\.withdrawAssets/);
  assert.match(assetsJs, /提现功能提示 T\+1 到账/);
  assert.match(assetsJs, /提现金额不能大于余额/);
  assert.doesNotMatch(assetsJs, /el\('button'[\s\S]{0,160}text:\s*'余额'/);
  assert.match(squareJs, /api\.publicSongs/);
  assert.match(squareJs, /api\.recordPublicPlay/);
  assert.match(publicSongJs, /api\.publicSong/);
  assert.match(publicSongJs, /api\.recordPublicPlay/);
  assert.match(publicSongJs, /gm-public-plays/);
  assert.match(publicSongJs, /toggleGlobalSong/);
  assert.match(marketJs, /api\.marketListings/);
  assert.match(marketJs, /api\.createMarketOrder/);
  assert.match(marketJs, /launchNexaPayment/);
  assert.match(marketJs, /toggleGlobalSong/);
  assert.match(marketJs, /bindMarketPlayerState/);
  assert.match(marketJs, /gm-global-player-state/);
  assert.match(marketJs, /gm-market-playing/);
  assert.match(marketJs, /data-song-id/);
  assert.match(marketJs, /gm-market-lyrics/);
  assert.match(marketJs, /gm-market-share/);
  assert.match(marketJs, /api\.publicSongLyrics/);
  assert.match(marketJs, /const url = `\$\{location\.origin\}\/ai-music\/song\//);
  assert.match(squareJs, /songs\.forEach\(\(song,\s*index\)/);
  assert.match(squareJs, /loading:\s*index\s*<\s*4\s*\?\s*'eager'\s*:\s*'lazy'/);
  assert.match(squareJs, /fetchpriority:\s*index\s*<\s*4\s*\?\s*'high'\s*:\s*'auto'/);
  assert.match(marketJs, /listings\.forEach\(\(listing,\s*index\)/);
  assert.match(marketJs, /loading:\s*index\s*<\s*4\s*\?\s*'eager'\s*:\s*'lazy'/);
  assert.match(marketJs, /fetchpriority:\s*index\s*<\s*4\s*\?\s*'high'\s*:\s*'auto'/);
  assert.match(libraryJs, /songs\.forEach\(\(s,\s*index\)/);
  assert.match(libraryJs, /const coverLoading = index < 4 \? 'eager' : 'lazy'/);
  assert.match(libraryJs, /fetchpriority="\$\{coverPriority\}"/);
  assert.match(styles, /\.gm-market-cover\.gm-market-playing/);
  assert.match(styles, /\.gm-market-actions/);
  assert.match(styles, /\.gm-market-sub-actions/);
  assert.match(playerJs, /id:\s*'gm-mini-player'/);
  assert.match(playerJs, /class:\s*'gm-mini-lyric'/);
  assert.match(playerJs, /new Audio/);
  assert.match(playerJs, /buildAudioCandidates/);
  assert.match(playerJs, /playCandidate/);
  assert.match(playerJs, /\/api\/ai-music\/public\/media\?u=/);
  assert.match(playerJs, /\/api\/ai-music\/media\?u=/);
  assert.match(playerJs, /expectedAudio\s*!==\s*audio/);
  assert.doesNotMatch(playerJs, /audio\.addEventListener\('error',\s*\(\)\s*=>\s*\{[\s\S]*toast\('音频加载失败'/);
  assert.match(styles, /\.gm-mini-player/);
  assert.match(styles, /\.gm-mini-lyric-track/);
  assert.match(styles, /body\.gm-has-mini-player \.gm-main\{padding-bottom:calc\(168px \+ env\(safe-area-inset-bottom\)\)/);
  assert.match(styles, /@media\(max-width:680px\)\{[\s\S]*body\.gm-has-mini-player \.gm-main\{padding-bottom:calc\(190px \+ env\(safe-area-inset-bottom\)\)/);
  assert.match(styles, /\.gm-market-card/);
  assert.match(styles, /\.gm-market\{[^}]*min-height:calc\(100svh - 96px\)[^}]*-webkit-overflow-scrolling:touch[^}]*overscroll-behavior-y:contain/);
  assert.match(styles, /\.gm-assets-card/);
  assert.match(styles, /\.gm-assets-row/);
  assert.match(styles, /@keyframes\s+gmMiniLyricScroll/);
});

test('ai music square supports mobile pull-up loading', () => {
  const squareJs = readPublicAiMusicFile('assets/square.js');
  const styles = readPublicAiMusicFile('assets/styles.css');

  assert.match(squareJs, /IntersectionObserver/);
  assert.match(squareJs, /gm-square-sentinel/);
  assert.match(squareJs, /author_nickname/);
  assert.match(squareJs, /作者：/);
  assert.doesNotMatch(squareJs, /text:\s*'播放'/);
  assert.match(squareJs, /gm-square-author-row/);
  assert.match(squareJs, /gm-square-title-row[\s\S]*gm-square-title[\s\S]*plays/);
  assert.match(squareJs, /el\('span',\s*\{\s*class:\s*'gm-square-title'/);
  assert.doesNotMatch(squareJs, /class:\s*'gm-square-title'[\s\S]*href:\s*`\/ai-music\/song\//);
  assert.match(squareJs, /gm-square-share/);
  assert.match(squareJs, /const url = `\$\{location\.origin\}\/ai-music\/song\//);
  assert.match(squareJs, /gm-square-lyrics/);
  assert.match(squareJs, /api\.publicSongLyrics/);
  assert.match(squareJs, /function cleanLyricsText/);
  assert.match(squareJs, /function normalizeLyricsValue/);
  assert.match(squareJs, /value\.result/);
  assert.match(squareJs, /value\.lines/);
  assert.match(squareJs, /class=\|style=/);
  assert.match(squareJs, /gm-square-author-row[\s\S]*gm-square-author[\s\S]*gm-square-actions[\s\S]*gm-square-lyrics[\s\S]*gm-square-share/);
  assert.match(squareJs, /class:\s*'hh-my-create-btn'[\s\S]*text:\s*'写歌'/);
  assert.match(squareJs, /gm-square-plays/);
  assert.match(squareJs, /gm-square-favorite/);
  assert.match(squareJs, /api\.favorite/);
  assert.match(squareJs, /gm-global-player-state/);
  assert.match(squareJs, /data-song-id/);
  assert.match(squareJs, /gm-square-playing/);
  assert.match(squareJs, /我在 https:\/\/claw800\.com\/ai-music\/ 发现了一首歌/);
  assert.doesNotMatch(squareJs, /我在 claw800\.com 用 AI 1 分钟做了首歌/);
  assert.match(styles, /\.gm-square-cover\.gm-square-playing/);
  assert.match(squareJs, /formatPlayCount/);
  assert.match(squareJs, /playPublicSong/);
  assert.match(squareJs, /setTimeout\(\(\)\s*=>\s*go\(\),\s*320\)/);
  assert.match(squareJs, /onerror:\s*\(event\)\s*=>/);
  assert.match(squareJs, /el\('img'/);
  assert.match(styles, /\.gm-square-author-row[\s\S]*align-items:\s*center[\s\S]*justify-content:\s*space-between/);
  assert.match(styles, /\.gm-square-title-row/);
  assert.match(styles, /\.gm-square-cover\{[^}]*width:68px[^}]*height:68px/);
  assert.match(styles, /@media\(max-width:680px\)[\s\S]*\.gm-square-cover\{width:62px;height:62px;flex-basis:62px/);
  assert.match(styles, /\.gm-square-side/);
  assert.match(styles, /\.gm-square-actions/);
  assert.match(styles, /\.gm-square-lyrics-card/);
  assert.match(styles, /\.gm-square-plays/);
  assert.match(styles, /\.gm-square-share/);
  assert.match(styles, /@media\(max-width:680px\)[\s\S]*\.gm-square-search\{grid-template-columns:minmax\(0,1fr\) auto/);
  assert.match(squareJs, /loadMore/);
  assert.match(squareJs, /append:\s*true/);
  assert.match(squareJs, /scrollIntoView/);
  assert.match(styles, /\.gm-square-sentinel/);
  assert.match(styles, /\.gm-square-author/);
  assert.match(styles, /-webkit-overflow-scrolling:\s*touch/);
});

test('ai music library search and create button match square layout', () => {
  const libraryJs = readPublicAiMusicFile('assets/library.js');
  const myMusicCss = readPublicAiMusicFile('assets/my-music.css');
  const actionBarBody = libraryJs.match(/function actionBar\(s\) \{[\s\S]*?\n}\n\n\/\/ WAV/)?.[0] || '';

  assert.match(libraryJs, /class:\s*'gm-head hh-my-top-head'/);
  assert.match(libraryJs, /class:\s*'hh-my-create-btn'[\s\S]*text:\s*'写歌'/);
  assert.match(libraryJs, /class:\s*'gm-square-search hh-my-search-unified'/);
  assert.match(libraryJs, /class:\s*'gm-input'/);
  assert.match(libraryJs, /class:\s*'gm-btn-ghost'[\s\S]*text:\s*'搜索'/);
  assert.match(actionBarBody, /class="[^"]*hh-btn-sell[^"]*"[\s\S]*data-act="sell"[\s\S]*>出售</);
  assert.match(libraryJs, /const MODAL_INPUT = '[^']*font-size:16px/);
  assert.match(libraryJs, /id="sell-price"[^>]*inputmode="decimal"/);
  assert.match(libraryJs, /openSellModal/);
  assert.match(libraryJs, /api\.listSong/);
  assert.match(libraryJs, /gm-public-toggle/);
  assert.match(libraryJs, /hh-my-title-row[\s\S]*hh-music-title[\s\S]*hh-my-title-fav[\s\S]*gm-public-toggle/);
  assert.match(libraryJs, /gm-public-toggle-text[\s\S]*公开到广场[\s\S]*gm-public-toggle-track/);
  assert.match(libraryJs, /api\.setSongPublic/);
  assert.match(libraryJs, /data-act="public-toggle"/);
  assert.match(myMusicCss, /\.hh-my-title-row\s*\{[\s\S]*display:\s*flex/);
  assert.match(myMusicCss, /\.hh-my-title-fav\s*\{[\s\S]*position:\s*static\s*!important/);
  assert.match(myMusicCss, /\.gm-public-toggle\s*\{[\s\S]*flex-direction:\s*row/);
  assert.match(actionBarBody, /data-act="rename"[\s\S]*>改名</);
  assert.match(actionBarBody, /data-act="delete"[\s\S]*>删除</);
  assert.match(actionBarBody, /data-act="delete"[\s\S]*data-act="sell"[\s\S]*>出售</);
  assert.doesNotMatch(actionBarBody, /data-cat-toggle/);
  assert.doesNotMatch(actionBarBody, /hh-cat-more-wrap/);
  assert.doesNotMatch(actionBarBody, /下载/);
  assert.doesNotMatch(actionBarBody, /data-act="copyright"/);
  assert.doesNotMatch(actionBarBody, /data-act="stem-split"/);
  assert.doesNotMatch(actionBarBody, /data-act="stem-inst"/);
  assert.match(myMusicCss, /\.hh-my-toolbar-flat/);
  assert.match(myMusicCss, /\.hh-my-top-head/);
  assert.match(myMusicCss, /\.hh-my-search-unified/);
  assert.match(myMusicCss, /\.hh-my-wrap\s*\{[\s\S]*min-height:\s*calc\(100svh - 96px\)[\s\S]*-webkit-overflow-scrolling:\s*touch[\s\S]*overscroll-behavior-y:\s*contain/);
  assert.match(myMusicCss, /\.hh-btn-sell/);
  assert.match(myMusicCss, /\.hh-card-bar \.hh-btn-sell/);
  assert.match(myMusicCss, /\.hh-bar-btn-danger/);
});

test('ai music library downloads use direct attachment links for mobile webviews', () => {
  const libraryJs = readPublicAiMusicFile('assets/library.js');
  const proxyDownloadBody = libraryJs.match(/async function proxyDownload[\s\S]*?\n}\n/)?.[0] || '';

  assert.match(proxyDownloadBody, /searchParams\.set\('download',\s*'1'\)/);
  assert.match(proxyDownloadBody, /searchParams\.set\('filename',\s*filename\)/);
  assert.match(proxyDownloadBody, /a\.target\s*=\s*'_blank'/);
  assert.doesNotMatch(proxyDownloadBody, /fetch\(mediaUrl\(rawUrl\)\)/);
  assert.doesNotMatch(proxyDownloadBody, /URL\.createObjectURL/);
});
