const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const rootDir = path.join(__dirname, '..');
const htmlPath = path.join(rootDir, 'public', 'u-card-query', 'index.html');
const cssPath = path.join(rootDir, 'public', 'u-card-query', 'style.css');
const jsPath = path.join(rootDir, 'public', 'u-card-query', 'script.js');
const uCardApplyHtmlPath = path.join(rootDir, 'public', 'u', 'index.html');
const adminHtmlPath = path.join(rootDir, 'public', 'admin.html');
const adminJsPath = path.join(rootDir, 'public', 'admin.js');
const serverPath = path.join(rootDir, 'src', 'server.js');

test('U card query route stays separate from U card application route', () => {
  const server = fs.readFileSync(serverPath, 'utf8');
  assert.match(server, /app\.get\(\['\/u-card-query', '\/u-card-query\/'\][\s\S]*public', 'u-card-query', 'index\.html'/);
  assert.match(server, /app\.get\(\['\/u', '\/u\/'\][\s\S]*public', 'u', 'index\.html'/);
  assert.doesNotMatch(server, /res\.redirect\(301, '\/u'\)/);
});

test('U card application page is a separate mobile entry with all and my card tabs', () => {
  const html = fs.readFileSync(uCardApplyHtmlPath, 'utf8');
  assert.match(html, /<title>U 卡申请<\/title>/);
  assert.match(html, /data-tab="all"[\s\S]*所有卡/);
  assert.match(html, /data-tab="mine"[\s\S]*我的卡/);
  assert.doesNotMatch(html, /class="back-link"/);
  assert.doesNotMatch(html, /返回游戏与工具/);
  assert.doesNotMatch(html, /<h1>U 卡申请<\/h1>/);
  assert.doesNotMatch(html, /u卡场景查询/);
});

test('U card application page connects Nexa login through configured claw800 API', () => {
  const html = fs.readFileSync(uCardApplyHtmlPath, 'utf8');
  assert.match(html, /id="uCardLoginBtn"/);
  assert.match(html, /const NEXA_PROTOCOL_AUTH_BASE = 'nexaauth:\/\/oauth\/authorize';/);
  assert.match(html, /const NEXA_PUBLIC_CONFIG_ENDPOINT = '\/api\/nexa\/public-config';/);
  assert.match(html, /fetch\(NEXA_PUBLIC_CONFIG_ENDPOINT/);
  assert.match(html, /redirect_uri=\$\{encodeURIComponent\(redirectUri\)\}/);
  assert.match(html, /\/api\/nexa\/tip\/session/);
  assert.match(html, /gameSlug:\s*'u-card'/);
  assert.match(html, /function extractAuthCodeFromUrl\(\)/);
  assert.match(html, /clearAuthCodeFromUrl\(\)/);
});

test('U card application page loads and renders upstream products', () => {
  const html = fs.readFileSync(uCardApplyHtmlPath, 'utf8');
  assert.match(html, /const U_CARD_PRODUCTS_ENDPOINT = '\/api\/u-card\/products';/);
  assert.match(html, /const U_CARD_HOLDER_OPTIONS_ENDPOINT = '\/api\/u-card\/holder-options';/);
  assert.match(html, /id="uCardAllList"/);
  assert.match(html, /id="uCardAllStatus"/);
  assert.match(html, /function renderUCardProducts\(products = \[\]\)/);
  assert.match(html, /fetch\(U_CARD_PRODUCTS_ENDPOINT/);
  assert.match(html, /product\.fee_amount/);
  assert.match(html, /loadUCardProducts\(\);/);
});

test('U card application requires payment before showing cardholder form', () => {
  const html = fs.readFileSync(uCardApplyHtmlPath, 'utf8');
  assert.match(html, /const NEXA_PROTOCOL_ORDER_BASE = 'nexaauth:\/\/order';/);
  assert.match(html, /const U_CARD_PAYMENT_CREATE_ENDPOINT = '\/api\/u-card\/payment\/create';/);
  assert.match(html, /const U_CARD_PAYMENT_QUERY_ENDPOINT = '\/api\/nexa\/tip\/query';/);
  assert.match(html, /const U_CARD_APPLICATIONS_ENDPOINT = '\/api\/u-card\/applications';/);
  assert.match(html, /function beginUCardPayment\(productCode, button\)/);
  assert.match(html, /window\.location\.href = buildNexaPaymentUrl\(response\.payment\);/);
  assert.match(html, /function confirmUCardApplicationPayment\(applicationNo\)/);
  assert.match(html, /function recoverPaidUCardApplication\(pending\)/);
  assert.match(html, /async function loadMyCards\(options = \{\}\)/);
  assert.match(html, /if \(fast\) params\.set\('fast', '1'\)/);
  assert.match(html, /loadMyCards\(\{ fast: false, silent: true, backgroundRefresh: false \}\)/);
  assert.match(html, /const U_CARD_REVIEW_POLL_INTERVAL_MS = 5 \* 60 \* 1000;/);
  assert.match(html, /function scheduleUCardReviewPolling\(\)/);
  assert.match(html, /window\.setInterval\(async \(\) => \{[\s\S]*loadMyCards\(\{ fast: false, silent: true, backgroundRefresh: false \}\)/);
  assert.doesNotMatch(html, /formatApplicationStatus/);
  assert.match(html, /系统会每 5 分钟继续查询上游结果/);
  const server = fs.readFileSync(serverPath, 'utf8');
  assert.match(server, /const U_CARD_REVIEW_POLL_INTERVAL_MS = 5 \* 60 \* 1000;/);
  assert.match(server, /function pollDueUCardApplicationReviews\(\)/);
  assert.match(server, /setInterval\(\(\) => \{[\s\S]*pollDueUCardApplicationReviews\(\)/);
  assert.match(server, /next_review_check_at = datetime\('now', '\+5 minutes'\)/);
  assert.match(html, /function openCardholderForm\(application\)/);
  assert.match(html, /let paidApplicationToProfile = null;/);
  assert.match(html, /paidApplicationToProfile = confirmedItem;/);
  assert.match(html, /if \(paidApplicationToProfile\) openCardholderForm\(paidApplicationToProfile\);/);
  assert.match(html, /支付成功，请补充用卡人资料。/);
  assert.match(html, /holderChannelBadge/);
  assert.match(html, /passportSignaturePage/);
  assert.match(html, /handheldPassportPhoto/);
  assert.match(html, /readUCardHolderFileAsDataUrl/);
  assert.match(html, /isUCardChannelTwo\(activePaidApplication\)/);
  assert.match(html, /data-fill-profile/);
  assert.match(html, /submitUCardHolderProfile\(activePaidApplication\.application_no, formData\)/);
  assert.match(html, /await loadMyCards\(\);\s*closeCardholderForm\(\);\s*selectTab\('mine'\);/);
  assert.match(html, /scheduleUCardReviewPolling\(\);/);
  assert.match(html, /function scrollFocusedHolderFieldIntoView\(field\)/);
  assert.match(html, /holderForm\.addEventListener\('focusin',/);
  assert.match(html, /window\.visualViewport\.addEventListener\('resize',/);
  assert.match(html, /scroll-padding-bottom: 140px;/);
  assert.match(html, /id="uCardHolderModal"/);
  assert.match(html, /<span class="required">\*<\/span> 名字/);
  assert.match(html, /<span class="required">\*<\/span> 姓氏/);
  assert.match(html, /<span class="required">\*<\/span> 国籍/);
  assert.match(html, /<span class="required">\*<\/span> 生日/);
  assert.match(html, /<span class="required">\*<\/span> 手机号/);
  assert.match(html, /<select id="holderPhoneCode" name="phoneCode" required aria-label="区号">/);
  assert.match(html, /<option value="\+86" selected>\+86<\/option>/);
  assert.match(html, /function sortPhoneCountryCodeOptions\(items\)/);
  assert.match(html, /function setDefaultHolderPhoneCode\(\)/);
  assert.match(html, /renderOptionList\(document\.getElementById\('holderPhoneCode'\), sortPhoneCountryCodeOptions\(payload\.phoneCountryCodes\),/);
  assert.match(html, /\['\+1', '\+61', '\+65', '\+81', '\+86', '\+852'\]/);
  assert.match(html, /setDefaultHolderPhoneCode\(\);/);
  assert.match(html, /function renderCountryOptionList\(target, items = \[\]/);
  assert.match(html, /renderCountryOptionList\(document\.getElementById\('holderNationality'\), payload\.countries/);
  assert.match(html, /renderCountryOptionList\(document\.getElementById\('holderCountry'\), payload\.countries/);
  assert.doesNotMatch(html, /holderPhoneCodeSelect/);
  assert.match(html, /function loadUCardHolderOptions\(\)/);
  assert.match(html, /fetch\(U_CARD_HOLDER_OPTIONS_ENDPOINT/);
  assert.match(html, /<span class="required">\*<\/span> 邮箱/);
  assert.match(html, /<span class="required">\*<\/span> 国家\/地区/);
  assert.match(html, /<span class="required">\*<\/span> 省份\/州/);
  assert.match(html, /<span class="required">\*<\/span> 城市/);
  assert.match(html, /<span class="required">\*<\/span> 邮政编码/);
  assert.match(html, /<span class="required">\*<\/span> 详细地址/);
  assert.match(html, /\.form-row input,\s*\.form-row select\s*\{[\s\S]*font-size:\s*16px;/);
});

test('U card my cards waits briefly for Nexa session before showing an empty list', () => {
  const html = fs.readFileSync(uCardApplyHtmlPath, 'utf8');
  assert.match(html, /const U_CARD_SESSION_WAIT_TIMEOUT_MS = 2000;/);
  assert.match(html, /let nexaSessionSyncPromise = null;/);
  assert.match(html, /let nexaSessionSyncInFlight = false;/);
  assert.match(html, /async function waitForNexaSessionSync\(timeoutMs = U_CARD_SESSION_WAIT_TIMEOUT_MS\)/);
  assert.match(html, /if \(!session\?\.openId && nexaSessionSyncInFlight\) \{[\s\S]*setMineCardsStatus\('正在加载我的卡\.\.\.'\)/);
  assert.match(html, /session = await waitForNexaSessionSync\(\);/);
  assert.match(html, /nexaSessionSyncInFlight \? '正在完成 Nexa 登录\.\.\.' : '申请成功后，卡会显示在这里。'/);
  assert.match(html, /nexaSessionSyncInFlight = true;\s*nexaSessionSyncPromise = syncSessionFromAuthCode\(\)\.finally\(\(\) => \{/);
  assert.match(html, /nexaSessionSyncPromise\.then\(\(\) => loadMyCards\(\)\)\.then\(settlePendingPayment\);/);
});

test('U card application page exposes approved card upstream actions', () => {
  const html = fs.readFileSync(uCardApplyHtmlPath, 'utf8');
  assert.match(html, /data-recharge-card/);
  assert.match(html, /data-review-pending-card/);
  assert.match(html, />审核中<\/button>/);
  assert.match(html, /data-view-secure/);
  assert.match(html, /status === 'review_pending'[\s\S]*data-view-secure=/);
  assert.match(html, /正在审核中，无法查看卡信息。/);
  assert.match(html, /if \(item\?\.status === 'review_pending'\)/);
  assert.match(html, /data-view-ledger/);
  assert.match(html, />查看卡信息<\/button>/);
  assert.match(html, /id="uCardInfoModal"/);
  assert.match(html, /id="uCardInfoCardNoCopy"/);
  assert.match(html, /aria-label="复制卡号"/);
  assert.match(html, /id="uCardRechargeModal"/);
  assert.match(html, /const U_CARD_RECHARGE_FEE_RATE_DEFAULT = 0\.02;/);
  assert.match(html, /id="uCardRechargeNetAmount"/);
  assert.match(html, /充值金额[\s\S]*USDT/);
  assert.match(html, /到账金额[\s\S]*USD/);
  assert.match(html, /function calculateUCardRechargeNetAmount\(amount, feeRate = U_CARD_RECHARGE_FEE_RATE_DEFAULT\)/);
  assert.match(html, /function syncUCardRechargeNetAmount\(\)/);
  assert.match(html, /uCardRechargeAmountInput\.addEventListener\('input', syncUCardRechargeNetAmount\)/);
  assert.match(html, /id="uCardLedgerModal"/);
  assert.match(html, /id="uCardLedgerList"/);
  assert.match(html, /const U_CARD_RECHARGE_PAYMENT_CREATE_ENDPOINT = '\/api\/u-card\/applications\/:applicationNo\/recharge-payment\/create';/);
  assert.match(html, /const U_CARD_RECHARGE_PAYMENT_TIMEOUT_MS = 2 \* 60 \* 1000;/);
  assert.match(html, /function openUCardInfoModal\(application, payload\)/);
  assert.match(html, /function copyUCardInfoCardNo\(\)/);
  assert.match(html, /navigator\.clipboard\.writeText/);
  assert.match(html, /flashUCardInfoMessage\('复制成功'\)/);
  assert.match(html, /infoCardNoCopyButton\.addEventListener\('click', copyUCardInfoCardNo\)/);
  assert.match(html, /function openUCardRechargeModal\(application\)/);
  assert.match(html, /function openUCardLedgerModal\(application, payload\)/);
  assert.match(html, /function getUCardLedgerItems\(payload\)/);
  assert.match(html, /时间/);
  assert.match(html, /类型/);
  assert.match(html, /金额/);
  assert.match(html, /余额/);
  assert.match(html, /状态/);
  assert.match(html, /function beginUCardRechargePayment\(application, amount\)/);
  assert.match(html, /expiresAt: Date\.now\(\) \+ U_CARD_RECHARGE_PAYMENT_TIMEOUT_MS/);
  assert.match(html, /pending\.type === 'recharge' && Number\(pending\.expiresAt \|\| 0\) <= Date\.now\(\)/);
  assert.match(html, /充卡支付超时，订单已取消/);
  assert.match(html, /function flashSessionStatus\(message, tone = '', duration = 3000\)/);
  assert.match(html, /flashSessionStatus\('充卡支付超时，订单已取消。', 'error'\)/);
  assert.match(html, /function getUCardSecureCardNo\(payload\)/);
  assert.match(html, /function getUCardSecureExpiry\(payload\)/);
  assert.match(html, /function getUCardSecureCvv\(payload\)/);
  assert.match(html, /function getUCardDetailCardId\(payload\)/);
  assert.match(html, /function getUCardDetailStatus\(payload\)/);
  assert.match(html, /function getUCardDetailBalance\(payload\)/);
  assert.match(html, /id="uCardInfoStatus"/);
  assert.match(html, /id="uCardInfoBalance"/);
  assert.match(html, /checkUCardReview/);
  assert.match(html, /function getUCardDisplayCardId\(item\)/);
  assert.match(html, /function getUCardDisplayCardNo\(item\)/);
  assert.match(html, /function getUCardDisplayBalance\(item\)/);
  assert.match(html, /卡 ID：/);
  assert.match(html, /卡号：/);
  assert.match(html, /余额：[\s\S]*formatUCardUsdAmount/);
  assert.doesNotMatch(html, /\$\{item\.card_no_masked \? `<p>卡号：/);
  assert.match(html, /callUCardAction\(secureButton\.dataset\.viewSecure, 'secure-info'\)/);
  assert.match(html, /window\.location\.href = buildNexaPaymentUrl\(response\.payment\);/);
  assert.match(html, /callUCardAction\(pending\.applicationNo, 'recharge', \{[\s\S]*?paymentAmount: pending\.amount[\s\S]*?creditAmount: pending\.creditAmount[\s\S]*?paymentOrderNo: pending\.orderNo[\s\S]*?\}\)/);
  assert.match(html, /callUCardAction\(ledgerButton\.dataset\.viewLedger, 'transactions'\)/);
  assert.doesNotMatch(html, /alert\(JSON\.stringify\(payload\.item \|\| payload, null, 2\)\)/);
});

test('U card recharge returns to my cards without local payment polling', () => {
  const html = fs.readFileSync(uCardApplyHtmlPath, 'utf8');
  const rechargeFunction = html.match(/async function beginUCardRechargePayment\(application, amount\) \{[\s\S]*?\n      \}/)?.[0] || '';
  const applyFunction = html.match(/async function beginUCardPayment\(productCode, button\) \{[\s\S]*?\n      \}/)?.[0] || '';
  assert.match(rechargeFunction, /window\.location\.href = buildNexaPaymentUrl\(response\.payment\);/);
  assert.match(rechargeFunction, /return;/);
  assert.doesNotMatch(rechargeFunction, /waitForPaymentSuccess/);
  assert.match(applyFunction, /window\.location\.href = buildNexaPaymentUrl\(response\.payment\);/);
  assert.match(applyFunction, /return;/);
  assert.doesNotMatch(applyFunction, /waitForPaymentSuccess/);
  assert.match(html, /await loadMyCards\(\);\s*selectTab\('mine'\);/);
  assert.match(html, /function selectPendingPaymentTab\(\)/);
  assert.match(html, /pending\?\.type === 'recharge'/);
  assert.match(html, /selectPendingPaymentTab\(\);\s*loadUCardProducts\(\);/);
  assert.match(html, /function schedulePendingPaymentSettle\(delayMs = 10000\)/);
  assert.match(html, /error\?\.statusCode === 429/);
  assert.match(html, /Nexa 请求频繁，稍后自动确认支付结果/);
});

test('U card query page includes language toggle after platform count', () => {
  const html = fs.readFileSync(htmlPath, 'utf8');
  assert.match(html, /<span id="platformCount">0<\/span>[\s\S]*?<div class="lang-toggle"/);
  assert.match(html, /id="langZh"[\s\S]*data-lang="zh"[\s\S]*>中<\/button>/);
  assert.match(html, /id="langEn"[\s\S]*data-lang="en"[\s\S]*EN/);
  assert.match(html, /id="platformSearch" class="platform-search" type="search"[\s\S]*aria-label="搜索平台"/);
  assert.match(html, /id="platformPager" class="platform-pager"/);
  assert.match(html, /\/u-card-query\/style\.css\?v=20260506-03/);
  assert.match(html, /\/u-card-query\/script\.js\?v=20260506-03/);
});

test('U card query script translates fixed UI and selected results', () => {
  const js = fs.readFileSync(jsPath, 'utf8');
  assert.match(js, /currentLang = localStorage\.getItem\('uCardQueryLang'\) === 'en' \? 'en' : 'zh'/);
  assert.match(js, /const PLATFORMS_PER_PAGE = 21/);
  assert.match(js, /const SWIPE_MIN_DISTANCE = 48/);
  assert.match(js, /function stripParenthetical\(value\)/);
  assert.match(js, /function displayPlatformName\(value\)/);
  assert.match(js, /selectPlatform:\s*'选择'/);
  assert.match(js, /selectPlatform:\s*'Select'/);
  assert.match(js, /searchPlaceholder:\s*'搜索'/);
  assert.match(js, /searchPlaceholder:\s*'Search'/);
  assert.match(js, /function getFilteredPlatforms\(\)/);
  assert.match(js, /platformSearch\.addEventListener\('input'/);
  assert.match(js, /renderPlatforms\(getFilteredPlatforms\(\)\)/);
  assert.match(js, /supportedCardsTitle:\s*\(name\) => `Cards that support \$\{name\}`/);
  assert.match(js, /clickPlatformHint:\s*'After clicking a platform, cards available for payment will appear here\.'/);
  assert.match(js, /\['微信', 'WeChat'\]/);
  assert.match(js, /fetch\('\/api\/translate'/);
  assert.match(js, /resultTitle\.textContent = platform \? t\('supportedCardsTitle', displayPlatformName\(platform\.name\)\) : t\('resultTitle'\)/);
  assert.match(js, /issuerRegionLabel:\s*'发行地'/);
  assert.match(js, /issuerRegionLabel:\s*'Issued in'/);
  assert.match(js, /\['香港', 'Hong Kong'\]/);
  assert.match(js, /<span class="bin">\$\{escapeHtml\(t\('binPrefix'\)\)\} \$\{escapeHtml\(card\.bin\)\}<\/span>/);
  assert.match(js, /<span class="issuer-region">\$\{escapeHtml\(t\('issuerRegionLabel'\)\)\} \$\{escapeHtml\(displayName\(card\.issuer_region\)\)\}<\/span>/);
  assert.match(js, /platformPager\.addEventListener\('click'/);
  assert.match(js, /function changePlatformPage\(delta\)/);
  assert.match(js, /platformPanel\.addEventListener\('touchstart'/);
  assert.match(js, /platformPanel\.addEventListener\('touchend'/);
  assert.match(js, /changePlatformPage\(deltaX < 0 \? 1 : -1\)/);
});

test('U card query CSS styles the language toggle compactly', () => {
  const css = fs.readFileSync(cssPath, 'utf8');
  assert.match(css, /\.section-actions\s*\{[\s\S]*?display:\s*inline-flex;[\s\S]*?gap:\s*8px;[\s\S]*?\}/);
  assert.match(css, /\.lang-toggle\s*\{[\s\S]*?border-radius:\s*999px;[\s\S]*?\}/);
  assert.match(css, /\.lang-toggle-btn\.active\s*\{[\s\S]*?background:\s*var\(--brand\);[\s\S]*?color:\s*#fff;[\s\S]*?\}/);
  assert.match(css, /\.platform-grid\s*\{[\s\S]*?grid-template-columns:\s*repeat\(3,\s*minmax\(0,\s*1fr\)\);[\s\S]*?\}/);
  assert.match(css, /\.platform-search\s*\{[\s\S]*?border-radius:\s*999px;[\s\S]*?\}/);
  assert.match(css, /\.platform-panel\s*\{[\s\S]*?touch-action:\s*pan-y;[\s\S]*?\}/);
  assert.match(css, /\.platform-pager\s*\{[\s\S]*?display:\s*flex;[\s\S]*?justify-content:\s*center;[\s\S]*?\}/);
  assert.match(css, /\.issuer-region\s*\{[\s\S]*?background:\s*#f6f8f6;[\s\S]*?\}/);
});

test('U card admin supports optional issuer region on add and edit forms', () => {
  const adminHtml = fs.readFileSync(adminHtmlPath, 'utf8');
  const adminJs = fs.readFileSync(adminJsPath, 'utf8');

  assert.match(adminHtml, /id="uCardIssuerRegionLabel"[\s\S]*name="issuerRegion"[\s\S]*value="美国"[\s\S]*value="香港"[\s\S]*value="新加坡"/);
  assert.match(adminHtml, /id="uCardSyncUpstreamBtn"[\s\S]*一键同步上游场景资料/);
  assert.match(adminHtml, /\/admin\.js\?v=20260602-02/);
  assert.match(adminJs, /uCardIssuerRegionLabel:\s*'发行地'/);
  assert.match(adminJs, /uCardIssuerRegionNone:\s*'不选择'/);
  assert.match(adminJs, /uCardSyncUpstreamBtn:\s*'一键同步上游场景资料'/);
  assert.match(adminJs, /\/api\/admin\/u-card\/sync-upstream/);
  assert.match(adminJs, /function renderUCardIssuerRegionOptions\(selectedValue = ''\)/);
  assert.match(adminJs, /id="uCardIssuerRegion-\$\{card\.id\}"/);
  assert.match(adminJs, /issuerRegion:\s*String\(document\.getElementById\(`uCardIssuerRegion-\$\{id\}`\)\?\.value \|\| ''\)\.trim\(\)/);
  assert.match(adminJs, /issuerRegion:\s*String\(formData\.get\('issuerRegion'\) \|\| ''\)\.trim\(\)/);
});
